### ISSUE TITLE
Doesn't download

### ISSUE THREAD

**Issue by shillshocked** [sam09/bandcamp-dl#4]
On attempting to download a track, I get:

Traceback (most recent call last):
  File "bandcamp.py", line 1, in <module>
    from bandcamp_dl import bandcampDownloader
  File "/home/phoenix/bin/bandcamp-dl-master/bandcamp_dl/**init**.py", line 1, in <module>
    from .bandcampDownloader import Downloader
  File "/home/phoenix/bin/bandcamp-dl-master/bandcamp_dl/bandcampDownloader.py", line 70
    print path
             ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by shillshocked** [comment]
Never mind, needed to use Python 2
